security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    in_memory:
      memory:
        users:
          guest:
            password: guest
            roles: 'ROLE_USER'
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      # anonymous: true

      form_login:
        login_path: login
        check_path: login

      http_basic: ~

  access_control:
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^, roles: ROLE_USER }
