#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: folder_action
    # make a permanent redirection...
    permanent: false
    # ...and keep the original query string parameters
    keepQueryParams: true
